#pragma once

#define BATCH_MAX_LATENCY_SIZE 256
#define BATCH_MAX_BALANCED_SIZE 1024
#define BATCH_MAX_THROUGHPUT_SIZE 4096

#define FLUSH_US_LATENCY 50
#define FLUSH_US_BALANCED 200
#define FLUSH_US_THROUGHPUT 1000

#if defined(PIPELINE_MODE_LATENCY)

  #define BATCH_MAX BATCH_MAX_LATENCY_SIZE
  #define FLUSH_US FLUSH_US_LATENCY

#elif defined(PIPELINE_MODE_THROUGHPUT)

  #define BATCH_MAX BATCH_MAX_THROUGHPUT_SIZE
  #define FLUSH_US FLUSH_US_THROUGHPUT

#else

  #define BATCH_MAX BATCH_MAX_BALANCED_SIZE
  #define FLUSH_US FLUSH_US_BALANCED

#endif

#if (BATCH_MAX & (BATCH_MAX - 1)) != 0
  #error "BATCH_MAX must be a power of two"
#endif