if [ "$(basename "$PWD")" == "scripts" ]; then
    cd ..
fi

HFT_ISOLATED_PATH="${HFT_ISOLATED_PATH:-0}"
HFT_ISO_VETH_RX="${HFT_ISO_VETH_RX:-veth-rx}"

if [ "$HFT_ISOLATED_PATH" != "0" ]; then
    export HFT_AFXDP_IFACE="${HFT_AFXDP_IFACE:-$HFT_ISO_VETH_RX}"
    ./scripts/setup_isolated_path.sh
else
    export HFT_AFXDP_IFACE="${HFT_AFXDP_IFACE:-lo}"
fi

export HFT_AFXDP_QUEUE="${HFT_AFXDP_QUEUE:-0}"
export HFT_AFXDP_FORCE_ZEROCOPY="${HFT_AFXDP_FORCE_ZEROCOPY:-0}"
export HFT_AFXDP_PREFER_SKB="${HFT_AFXDP_PREFER_SKB:-1}"

echo "HFT_AFXDP_IFACE=$HFT_AFXDP_IFACE"
echo "HFT_AFXDP_FORCE_ZEROCOPY=$HFT_AFXDP_FORCE_ZEROCOPY"
echo "HFT_AFXDP_PREFER_SKB=$HFT_AFXDP_PREFER_SKB"
echo "HFT_ISOLATED_PATH=$HFT_ISOLATED_PATH"
./build/bin/client
